//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemThi
    {
        public int ID { get; set; }
        public string SBD { get; set; }
        public int ID_Mon { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual MonThi MonThi { get; set; }
        public virtual ThiSinh ThiSinh { get; set; }
    }
}
